fix:ui spacing and dark mode badge design
GNOME-Nepal/website pull request #52
Opened 2024-10-25 07:19 UTC by aayush105

## Title: Improve UI Spacing and Dark Mode Badge Design

### Summary
This PR refines the UI by adjusting spacing and enhancing the appearance of badges for dark mode. It addresses visual consistency by minimizing unnecessary gaps, aligning sections, and improving badge readability in dark mode.

### Changes Made
1. **Removed Unnecessary Spacing**: Reduced excess spacing between sections for a cleaner, more compact layout.
2. **Dark Mode Badge Updates**:
   - Modified badge text color for better contrast in dark mode.
   - Adjusted badge background color to ensure readability in both light and dark modes.
3. **Fixed Section Gaps**: Updated gapping between sections to improve consistency.

### Preview (Before and After)
#### Before:
![Screenshot 2024-10-24 161511](https://github.com/user-attachments/assets/0e3ac6a2-b1e4-45ef-9b65-1ce8e93a5659)

![Screenshot 2024-10-25 125652](https://github.com/user-attachments/assets/395f4d55-1e65-4ac4-b799-ae0ff2325b44)

![Screenshot 2024-10-25 125659](https://github.com/user-attachments/assets/bc216a0c-5000-4b7e-afdc-2a416d2b8219)

#### After:
![Screenshot 2024-10-24 161531](https://github.com/user-attachments/assets/812fc6fd-56a1-4dc5-936a-7c6629654bf9)

![Screenshot 2024-10-25 125447](https://github.com/user-attachments/assets/93714733-ddee-4e8a-a990-86e6f7249559)

![Screenshot 2024-10-25 125453](https://github.com/user-attachments/assets/a116d5f5-17d5-46cf-a303-451050cae2dc)

2024-10-25 11:12 UTC, utsavdotdev commented
Hi @aayush105, thanks for raising the PR! It would be best if you first created an issue before raising the PR, as this is the standard process for contributions. No worries! Could you also resolve the alignment issue on larger screens, as shown in the image below?

<img width="904" alt="Screenshot 2024-10-25 at 4 52 13 PM" src="https://github.com/user-attachments/assets/7730f406-54bc-4414-99a3-c04a4d507ab1">

2024-10-25 11:16 UTC, utsavdotdev requested changes
In the event section,  the RSVP should not be in outline

2024-10-25 11:18 UTC, utsavdotdev commented on src/sections/Events.jsx
> +                    <Button variant="outline">
This button should be as default not outline

2024-10-25 14:51 UTC, aayush105 commented
> Hi @aayush105, thanks for raising the PR! It would be best if you first created an issue before raising the PR, as this is the standard process for contributions. No worries! Could you also resolve the alignment issue on larger screens, as shown in the image below?
> 
> <img alt="Screenshot 2024-10-25 at 4 52 13 PM" width="904" src="https://private-user-images.githubusercontent.com/95236817/380132492-7730f406-54bc-4414-99a3-c04a4d507ab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTU1NzEsIm5iZiI6MTcyOTg1NTI3MSwicGF0aCI6Ii85NTIzNjgxNy8zODAxMzI0OTItNzczMGY0MDYtNTRiYy00NDE0LTk5YTMtYzA0YTRkNTA3YWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDExMjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMDE5MDYwYzNiZTJkYjZjMjQxNDFiYWZlYTVlNThhZWUyZmEyNDdjODQ5OWE3YmU3YzY4OTNkYWVhNTFmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PHGb6pGztHPZm81Xb3fMIDC1ZFa4asUZk47dqyXyOXY">

Sure, I will fix all the issue and let you know.  @utsavdotdev

2024-10-25 14:58 UTC, utsavdotdev commented
Ok

2024-10-26 10:42 UTC, aayush105 commented
> Ok

Can you review it? I have made the changes @utsavdotdev

2024-10-26 10:55 UTC, utsavdotdev commented
Great work @aayush105 , and Congratulation on your first contribution in GNOME Nepal

2024-10-26 10:56 UTC, merged

2024-10-27 09:23 UTC, aayush105 commented
> Great work @aayush105 , and Congratulation on your first contribution in GNOME Nepal

Thank you broda @utsavdotdev